### ISSUE TITLE
Where to place the libs?

### ISSUE THREAD

**Issue by thecodrr** [ManagedBass/Demo.Xamarin.Android#1]

**Comment by MathewSachin** [comment]
The libs are to placed at `lib\<platform>\libbass.so`.

```
lib\armeabi\libbass.so
lib\armeabi-v7a\libbass.so
lib\x86\libbass.so
```

Sorry for not including a ReadMe. Would commit it ASAP.

**Comment by thecodrr** [comment]
Yeah, I was able to fix this, though I had to change the Build Action (from `None` to `AndroidNativeLibrary` too for each BASS lib. You should add that to README too.

**Comment by MathewSachin** [comment]
Done 👍
